server:
  port: 8082

spring:
  application:
    name: Product
  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
